### PR TITLE
scene: Remove RespondShareImage

### PR DESCRIPTION
**Pull request by hajimehoshi**
This requires platform-side change.

### CODE REVIEW

**Comment by wasedaigo** [comment]
The platform is calling both request/respond. I think the runtime should handle this. As it was not implemented somehow.

**Comment by hajimehoshi** [comment]
I think you no longer need to call respond for share-image command. The runtime doesn't have to handle this, and actually does not do.

**Comment by hajimehoshi** [comment]
Note that this change is for `feature_platform`, not `master`. So this does not affect the released version.

**Comment by wasedaigo** [comment]
Why do you think it is no longer needed?  It is a bug and the game is happened to be working right now. Respond needs to be properly handled.

**Comment by wasedaigo** [comment]
When we are sharing image, the game should pause, right?

**Pull request closed without merging**
