### PR TITLE
ui: Change HandleInput semantics 

### PR DESCRIPTION
**Pull request by hajimehoshi**
HandleInput should return true when the input handling propagation
should not happen, otherwise false. For buttons, if the button is
visible and the cursor is on the region, HandleInput should return
true, even when the button is not pressed.

This should not change the current behavior since no other GUI
components is under a button.
fc44c1d

See #1026 first.

### CODE REVIEW

**Comment by wasedaigo** [comment]
for phones/tables there is no cursor. what is the expected behavior for them?

**Comment by hajimehoshi** [comment]
Ah good point. In this case, we don't have to consider this since `CursorPosition` always return (0, 0).

Even on the desktops, forbidding propagation on the condition doesn't make sense as long as we don't have e.g., 'mousemove' event.

**Comment by wasedaigo** [comment]
Technically (0,0) is on the screen, why don't we have to consider it?

**Comment by hajimehoshi** [comment]
Well, if we needed to do this exactly, we would detect whether a mouse is available or not.

**Pull request closed without merging**
